M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Monday 29 January 2024 08:12:24 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-29T20:12:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.75Y-1.8
X2.75Y-2.55
X4.35Y-1.8
X4.35Y-2.55
M30
